# Generated by Django 5.2.10 on 2026-02-02 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Active'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emis', to='loans.loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='loans.loancategory'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Repayment',
        ),
    ]
